_target_: src.models.facial_landmark_regression_module.FacialLandmarkModule

net:
  _target_: src.models.components.resnet.FacialLandmarkRegressionModule
  num_landmarks: 98

loss: wing

nme_norm_factor: 90.509668

compile: True

num_landmarks: 98